### ISSUE TITLE
What was this supposed to be?

### ISSUE THREAD

**Issue by nitinthewiz** [beheh/pulley#1]
Hey,

I just came across this repo. I often go around looking for tools related to fever. What were you trying to make?

Nitin

**Comment by beheh** [comment]
Thanks for asking! I used this in the past to share posts from selected feed groups with a friend in a kind of "feed exchange". They'd subscribe to the output of this script and would be able to see all the posts I'd see for those feed groups.

I've added the `index.php` with the script I used in the past for this, although it's nearly 5 years old by now and might not work anymore.
